[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_API_BASE_URL = "https://onboarding-ecwl.onrender.com"
  VITE_APP_TITLE = "Onboarding Solution"

[context.deploy-preview.environment]
  VITE_API_BASE_URL = "https://onboarding-ecwl.onrender.com"
  VITE_APP_TITLE = "Onboarding Solution - Preview"